# Chapter-9 Standard Libraries
This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [1]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating project at `C:\Users\WoU_AI_ML`


## 9.1 Introduction

There are various functions and methods that are part of Julia already. A developer needs to use them directly rather than having to code for them. This chapter is a bird's eyeview of such methods. 

### Modules

Namespaces where a method or a type reside. Using a method or type outside the module may require explicit qualification. 

In [2]:
module m1
    function f()
        println("Defined as m1.f")
    end
    function g()
        println("Defined as m1.g")
    end
    function h()
        println("Defined as m1.h")
    end
    export f
end

module m2
    function f()
        println("Defined as m2.f")
    end
    function g()
        println("Defined as m2.g")
    end
    export g
end

Main.m2

In [3]:
names(m1)

2-element Vector{Symbol}:
 :f
 :m1

In [4]:
names(m2)

2-element Vector{Symbol}:
 :g
 :m2

In [5]:
f()

LoadError: UndefVarError: f not defined

In [6]:
m1.f()

Defined as m1.f


In [7]:
m2.f()

Defined as m2.f


In [8]:
using .m1

In [9]:
f()

Defined as m1.f


In [10]:
g()

LoadError: UndefVarError: g not defined

In [11]:
using Main.m2

In [12]:
g()

Defined as m2.g


In [13]:
using .m1: g

In [14]:
g()

Defined as m2.g


In [15]:
using .m1: h

In [16]:
h()

Defined as m1.h


## 9.2 Standard Modules

`Core`, `Base` and `Main` the bare minimum modules of a Julia shell. `m1` and `m2` here are submodules of `Main`.

In [17]:
varinfo()

| name |      size | summary |
|:---- | ---------:|:------- |
| Base |           | Module  |
| Core |           | Module  |
| Main |           | Module  |
| m1   | 6.380 KiB | Module  |
| m2   | 5.526 KiB | Module  |


In [18]:
x = 1

1

In [19]:
varinfo()

| name |      size | summary |
|:---- | ---------:|:------- |
| Base |           | Module  |
| Core |           | Module  |
| Main |           | Module  |
| m1   | 6.380 KiB | Module  |
| m2   | 5.526 KiB | Module  |
| x    |   8 bytes | Int64   |


## 9.3 System

The submodule that interacts with the operating system. System command execution being one of them. 

In [20]:
run(`cmd /c dir`)

 Volume in drive C is OS
 Volume Serial Number is 3E32-AD10

 Directory of C:\Users\WoU_AI_ML

01-10-2022  21:35    <DIR>          .
04-01-2022  00:10    <DIR>          ..
15-09-2022  21:18         5,025,322  Beverly Hills vaccinehesitensy final.ipynb
16-09-2022  00:07        11,854,818  Vineeth Reddy Python Assignment final.ipynb
15-12-2020  14:29             2,746 #wild fire.csv
19-11-2021  23:40    <DIR>          .anaconda
10-09-2022  12:21               320 .bash_history
16-02-2022  17:09    <DIR>          .cache
01-10-2022  21:36    <DIR>          .conda
18-09-2022  17:22                43 .condarc
16-02-2022  17:09    <DIR>          .config
19-11-2021  23:42    <DIR>          .continuum
21-12-2020  11:24               198 .gitconfig
28-09-2021  15:16    <DIR>          .IBM
12-02-2021  13:45    <DIR>          .idlerc
01-10-2022  21:35    <DIR>          .ipynb_checkpoints
28-11-2020  17:40    <DIR>          .ipython
09-09-2022  14:26    <DIR>          .julia
01-12-2020  17:13    <D

Process(`cmd /c dir`, ProcessExited(0))

In [21]:
Sys.isunix(), Sys.iswindows()

(false, true)

## 9.4 Filesystem

File organization and manipulation (not read and write). 

In [22]:
old_dir = pwd()

"C:\\Users\\WoU_AI_ML"

In [23]:
cd("..")

In [24]:
pwd()

"C:\\Users"

In [25]:
cd(old_dir)

In [26]:
pwd()

"C:\\Users\\WoU_AI_ML"

In [27]:
cd(".."); pwd()

"C:\\Users"

In [28]:
readdir()  #Same as readdir(pwd())

7-element Vector{String}:
 "All Users"
 "Default"
 "Default User"
 "Public"
 "WoU_AI_ML"
 "admin"
 "desktop.ini"

In [29]:
for (root, dirs, files) in walkdir("Chapter-09")
    println("Directories in $root")
    for dir in dirs
        println(joinpath(root, dir)) # path to directories
    end
    println("Files in $root")
    for file in files
        println(joinpath(root, file)) # path to files
    end
end

In [30]:
cd(old_dir); pwd()

"C:\\Users\\WoU_AI_ML"

In [31]:
fs = stat("Chapter-9 Standard Libraries.ipynb")

StatStruct for "Chapter-9 Standard Libraries.ipynb"
   size: 65258 bytes
 device: 1043508496
  inode: 1769667
   mode: 0o100666 (-rw-rw-rw-)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 128
  mtime:  (41 seconds ago)
  ctime:  (41 seconds ago)

## 9.5 Parallel Programming

Execution of programs in tandem in various execution environments, yet be able to obtain meaningful and synchronized results. Performance and resource utilization are two major outcomes of this kind of programming. 

### Asynchronous Programming

Breaking the code into small chunks of executable pieces that can be executed in parallel. Depending on the kind of processing permitted by the hardware and OS, these may run in one execution thread or multiple.

#### Tasks

In [32]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000c333270

In [33]:
schedule(t)

Task (runnable) @0x000000000c333270

In [34]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000b7b3650

In [35]:
schedule(t); wait(t)

done
done


In [36]:
t = @task begin
    sleep(5)
    println("done")
end

Task (runnable) @0x000000000b7b3e10

In [37]:
@sync  begin
    sleep(5)
    println("done")
end

done


#### Channels

In [38]:
c = Channel(8)

Channel{Any}(8) (empty)

In [39]:
c = Channel{Int}(4)

Channel{Int64}(4) (empty)

In [40]:
@async begin
    for i = 1:100
        println("Adding $i to channel")
        put!(c, i)
    end
end

@async begin
    for i = 1:100
        v = take!(c)
        println("Removing value: $v")
    end
end

Task (runnable) @0x000000000ca5eca0

Adding 1 to channel


In [41]:
close(c)

Adding 2 to channel
Adding 3 to channel
Removing value: 1


### Multithreading

Julia can be made to run on a multiple threads mode. In such a conditions the tasks can be parallelized on these threads. Synchronization objects can be used across the executing threads. 

In [42]:
Threads.nthreads()

Removing value: 2


1

In [43]:
Threads.@spawn for i=1:100
    sleep(1)
    println("Step: $i")
end

Task (runnable) @0x000000000d119940

### Distributed Computing

This is cluster computing infrastrcuture, where a cluster can be configured across Julia processes in the same machine or in another machine. These independent processes can execute independently yet be able to share data, pass messages and communicate over a shared channel. 

## 9.6 IO and Network

Julia accesses input and output devices as streams. The network devices are also interfaced like sockets. IO is an important stream based interface to understand. 

### Default Stream

`stdin`, `stdout` and `stderr` are the standard streams for input, output and error in most processes. `stdin` integration with Jupyter is limited. All those samples may best be reviewed in a REPL console. 

In [44]:
write(stdout, "Hello World")

Hello World

11

In [45]:
write(stdout, "\u2200 x \u2203 y")

∀ x ∃ y

11

### Text I/O

### Binary I/O

### File I/O

Files are also accessed as `IO` streams for both read and write operations. However, the `IO` streams are obtained by `open` call. Any open stream must be closed with a `close` function call. 

In [46]:
write("hello.txt", "Hello World")

11

In [47]:
fd = open("hello.txt", "r");
data = read(fd);

In [48]:
write(fd, "This is second line")

LoadError: ArgumentError: write failed, IOStream is not writeable

In [49]:
close(fd)
write(stdout, data)

Hello World

11

In [50]:
open("hello.txt", "r") do fd
    data = read(fd)
    write(stdout, data)
end

Hello World

11

In [51]:
write("hello.txt", "Hello World");
data = read("hello.txt");
write(stdout, data);

Hello World

Files are opened for `read` or `write`. A file opened for reading cannot be written into.  

In [52]:
open("hello.txt", "r") do fd
    while !eof(fd)
        b = read(fd, 1)
        write(stdout, b)
    end
end
rm("hello.txt")

Hello World

### Delimited Files

Generalized command separated value (CSV) kind of files. Used extensively in spreadsheets. Also interfaced in data science applications as an easier way to share data. 

In [53]:
using DelimitedFiles
x = collect(1:100);
y = Float64.(collect(101:200));
open("values.csv", "w") do f
    println(f, "X,Y")
    writedlm(f, [x y], ',')
end

In [54]:
data, header = readdlm("values.csv", ',', header=true);

In [55]:
size(data, 1)

100

In [56]:
header

1×2 Matrix{AbstractString}:
 "X"  "Y"

In [57]:
rm("values.csv")

Step: 1


### Network 

Just like files are opened with open to obtain the `IO` stream to interface, sockets are equivalent network communication end points to obtain connection streams. However, if you could use download method to provide a URL and download files. 

In [58]:
download("https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3.tar.gz", "julia-1.5.3.tar.gz")

Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7


"julia-1.5.3.tar.gz"

In [59]:
using Sockets
@async begin
    server = listen(3000)
    while true
        s = accept(server)
        @async while isopen(s)
            msg = readline(s, keep=true)
            write(s, "Server Response: $msg")
        end  
    end
end

Task (failed) @0x00000000d1560bb0
IOError: listen: address already in use (EADDRINUSE)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] #listen#13
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:629 [inlined]
 [3] #listen#10
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:622 [inlined]
 [4] #listen#12
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:626 [inlined]
 [5] #listen#11
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:625 [inlined]
 [6] listen
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:625 [inlined]
 [7] macro expansion
   @ .\In[59]:3 [inlined]
 [8] (::var"#19#21")()
   @ Main .\task.jl:484

In [60]:
c = connect(3000)
@async while isopen(c)
    println(stdout, readline(c, keep=true))
end

Task (runnable) @0x00000000d15e6100

In [61]:
for i = 1:5
    println(c, "Client Msg id: $i")
end

Server Response: Client Msg id: 1



In [62]:
close(c)

Server Response: Client Msg id: 2



### Memory I/O

Strings cannot be manipulated. It may help to create a byte array for `IO` in the memory and use that for text manipulations. In the end the byte array can be converted to a String. 

In [63]:
io = IOBuffer()
println(io, "This is Line 1")
println(io, "This is Line 2")
str = String(take!(io))

"This is Line 1\nThis is Line 2\n"

In [64]:
A = fill(10, (5, 20))
A[2, 3] = 20
open("mmap.bin", "w+") do fd
    write(fd, size(A, 1))
    write(fd, size(A, 2))
    write(fd, A)
end

800

Memory mapping is reverse problem. A file can be mapped to memory and accessed selectively page by page. This way the whole file need not be loaded in the memory. 

In [65]:
using Mmap
fd = open("mmap.bin", "r")
nr = read(fd, Int)
nc = read(fd, Int)
A2 = Mmap.mmap(fd, Matrix{Int}, (nr, nc))
println("A2[1, 1]: ", A2[1, 1], " A2[2, 3]: ", A2[2, 3])
close(fd)

A2[1, 1]: 10 A2[2, 3]: 20


In [66]:
A2 = nothing
GC.gc()
rm("mmap.bin")

## 9.7 Constants

There are many system and Julia related constants. Mathematical constants are also defined in the standard library. 

In [67]:
VERSION

v"1.8.0"

In [68]:
C_NULL

Step: 8


Ptr{Nothing} @0x0000000000000000

In [69]:
Sys.BINDIR

"C:\\Users\\WoU_AI_ML\\AppData\\Local\\Programs\\Julia-1.8.0\\bin"

In [70]:
Sys.CPU_THREADS

20

In [71]:
Sys.WORD_SIZE

64

In [72]:
Sys.KERNEL

:NT

In [73]:
Sys.MACHINE

"x86_64-w64-mingw32"

In [74]:
Sys.ARCH

:x86_64

In [75]:
Sys.ENV

Base.EnvDict with 68 entries:
  "=C:"                            => "C:\\Users\\WoU_AI_ML"
  "ALLUSERSPROFILE"                => "C:\\ProgramData"
  "AMOSAPP"                        => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSDOCS"                       => "C:\\Users\\WoU_AI_ML\\Documents\\AmosDev…
  "AMOSEXAMPLES"                   => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSLOGS"                       => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSPLUGINS"                    => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSPROGRAM"                    => "C:\\Program Files\\IBM\\SPSS\\Amos\\28"
  "AMOSTEMPLATES"                  => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSTUTORIAL"                   => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "APPDATA"                        => "C:\\Users\\WoU_AI_ML\\AppData\\Roaming"
  "COLUMNS"                        => "80"
  "COMMONPROGRAMFILES"             => "C:\\Program Files\\Common Files"
  "COMMONPROG

In [76]:
MathConstants.pi

π = 3.1415926535897...

In [77]:
MathConstants.e

ℯ = 2.7182818284590...

## 9.8 Notable Modules

Miscellaneous modules of Julia library. 

### Dates

User renderable date and time representations. In the system the date is just a continuously increasing counter from a datum. These functions make meaningful period associations and provide the correct date and time. 

In [78]:
using Dates

In [79]:
now()

2022-10-01T21:36:37.437

In [80]:
DateTime(2020)

Step: 9


2020-01-01T00:00:00

In [81]:
t = DateTime(2020, 10, 31, 01, 02, 03)

2020-10-31T01:02:03

In [82]:
Date(2020)

2020-01-01

In [83]:
d = Date(t)

2020-10-31

In [84]:
DateTime(d)

2020-10-31T00:00:00

In [85]:
t > d

true

In [86]:
DateTime(2020) < now()

true

In [87]:
DateTime(2020) == Date(2020)

true

In [88]:
p = Month(3) + Day(10) + Hour(15)

3 months, 10 days, 15 hours

In [89]:
typeof(p)

Dates.CompoundPeriod

In [90]:
now() + p

Step: 10


2023-01-12T12:36:38.708

In [91]:
Date(now())+ Day(300)

2023-07-28

In [92]:
now() - DateTime(2020)

86823398739 milliseconds

In [93]:
now() - Date(2020)

LoadError: MethodError: no method matching -(::DateTime, ::Date)
Closest candidates are:
  -(::StridedArray{<:Union{Dates.CompoundPeriod, Period}}, ::TimeType) at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\deprecated.jl:26
  -(::TimeType, ::Dates.CompoundPeriod) at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\periods.jl:400
  -(::T, ::T) where T<:TimeType at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\arithmetic.jl:9
  ...

In [94]:
Date(now()) - Date(2020)

1004 days

In [95]:
Year(now())

2022 years

In [96]:
Month(now())

10 months

In [97]:
Day(now())

Step: 11


1 day

In [98]:
Week(now())

39 weeks

In [99]:
year(now())

2022

In [100]:
tonext(today()) do d
    dayofweek(d) == Thursday &&
    dayofweekofmonth(d) == 4 &&
    month(d) == November
end

2022-11-24

### Logging

Long running processes or servers running in Julia need to provide consistent and standard log reporting. This module helps create such reports. 

In [101]:
@debug "This is a debug message $(sum(rand(100)))"

In [102]:
@info "This message is just informational"

┌ Info: This message is just informational
└ @ Main In[102]:1


In [103]:
@warn "This is a warning message"

┌ Warning: This is a warning message
└ @ Main In[103]:1


In [104]:
@error "This is an error message"

┌ Error: This is an error message
└ @ Main In[104]:1


In [105]:
A = ones(3, 4)
@info "A is all ones" A

┌ Info: A is all ones
│   A = [1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
└ @ Main In[105]:2


The `Logging` module provides interfaces to implement complete loggers. It also provides the ability to override the global logger with a different local one. 

In [106]:
using Logging

In [107]:
open("file.log", "w") do f
    with_logger(SimpleLogger(f)) do
        @info "This is my simple info log"
        @error "This is an error written to file"
        @warn "This is a warning message"
        @info "Current logger is same as global logger" current_logger() == global_logger()
    end
end
write(stdout, read("file.log"));

┌ Info: This is my simple info log
└ @ Main In[107]:3
┌ Error: This is an error written to file
└ @ Main In[107]:4
┌ Warning: This is a warning message
└ @ Main In[107]:5
┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = false
└ @ Main In[107]:6


In [108]:
rm("file.log")

In [109]:
@info "Current logger is same as global logger" current_logger() == global_logger()

┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = true
└ @ Main In[109]:1


### Statistics

This module provides simple functions for central tendencies like mean, median and standard deviations etc. Functions for correlations and covariances are also provided. However, the treatment of statistics in thi module are highly rudimentary. 

In [110]:
using Statistics

In [111]:
mean(1:10)

5.5

In [112]:
median(1:10)

5.5

In [113]:
std(1:10)

3.0276503540974917

In [114]:
var(1:10)

9.166666666666666

In [115]:
cor(1:10, rand(10))

-0.4661132564758624

In [116]:
cor(1:10, 11:20)

1.0

In [117]:
cov(1:10, rand(10))

-0.26954604605042487

Step: 12


### Random Numbers

Provides methods for random number generation and other permutation and combination functions. 

In [118]:
using Random

In [119]:
rand(Int, 2)

2-element Vector{Int64}:
 -1676632530474707123
  2319800912823674788

In [120]:
rand(2, 3)

2×3 Matrix{Float64}:
 0.892949  0.163384  0.116294
 0.667462  0.515968  0.130821

In [121]:
rand!(zeros(2, 3))

2×3 Matrix{Float64}:
 0.947901  0.92317   0.077077
 0.142879  0.836903  0.374337

In [123]:
rand(1:4, (2, 3))

2×3 Matrix{Int64}:
 3  4  2
 1  4  2

## 9.9 Conclusion

## Exercises